Video
Stas-Buzunko/cyber-school pull request #15
Opened 2017-04-19 14:49 UTC by MsZlets

2017-04-19 18:39 UTC, Stas-Buzunko requested changes
Видео компонент крутой!
нужно пофиксить остальные вещи

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/components/UserCoursesList.js
> +    firebase.database().ref('users/' + uid)
эм, ты понимаешь, что ты берешь объект юзера, чтобы взять его айди, чтобы загрузить объект юзера?
тебе не кажется это немного странным?)

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/components/UserCoursesList.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
var?)

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/components/UserCoursesList.js
> +          {Math.round(percent * 100)}% Complete (success)
Math.round(percent * 100)
это лучше сделать в переменной, а не в рендере

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    firebase.database().ref('users/' + uid)
аналогично. выше описал

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
var

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
что думаешь насчет того, чтобы выносить такие небольшие методы в отдельные папку utils?
чтобы не дублировать код

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +        </div>
Как насчет вынести в отдельный компонент ProgressBar?

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/index.js
> +        const MainView = require('./containers/MainViewContainer').default
супер!

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    const isLessonInWatchedLessonsIds = uniqueWatchedLessonsIds.findIndex(id => id === lessonId)
круто, не знал про findIndex

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +      return newArray
зачем для этого создавать переменную если ты с ней ничего не делаешь?
почему бы просто не вернуть новый массив?

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    firebase.database().ref('users/' + uid)
опять)) брать юзера чтобы взять айди чтобы загрузить юзера))

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    firebase.database().ref('users/' + uid)
убирай это)

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +      const { userCourses } = this.state
могут не успеть записаться в стейт, лучше сделать return userCourses в промисе, и тогда они передадутся в then как аргумент

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +          <VideoPlayer
супер, что вынесла в отдельный компонент

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +    this.props.addVideoId(isEnded = true)
это не выдает ошибку?
я просто такого не видел никогда.

1) почему сразу не написать const isEnded = true?
2) почему просто не передать true в параметрах?

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +    this.props.addVideoId(isEnded = false)
аналогично, смотри выше

2017-04-19 18:39 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +        {this.renderVideo()}
супер! чтобы более читабельный рендер был

2017-04-19 18:48 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +    firebase.database().ref('users/' + uid)
у меня по-другому нету его в стейте
он не обновляется

2017-04-19 20:50 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    const isLessonInWatchedLessonsIds = uniqueWatchedLessonsIds.findIndex(id => id === lessonId)
Знал ты))

2017-04-19 20:51 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +    this.props.addVideoId(isEnded = true)
1. линт подчеркивает

2. хочу переменную, чтобы потом не вспоминать долго что это за тру или фалз

2017-04-19 20:54 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
копировала с учебника

2017-04-19 20:57 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +          {Math.round(percent * 100)}% Complete (success)
ok

2017-04-19 21:34 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
!

2017-04-19 21:34 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +          {Math.round(percent * 100)}% Complete (success)
!

2017-04-19 21:35 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
!

2017-04-19 21:36 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    var numberLessonsInCourse = lessonsNumbersArray.reduce((a, b) => {
Давай от трех повторов выносить?

2017-04-19 21:36 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +        </div>
у меня они по-разному написаны из- за загрузки информации

2017-04-19 21:37 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/index.js
> +        const MainView = require('./containers/MainViewContainer').default
!

2017-04-19 21:37 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    const isLessonInWatchedLessonsIds = uniqueWatchedLessonsIds.findIndex(id => id === lessonId)
!

2017-04-19 21:41 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +      return newArray
!

2017-04-19 21:43 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +      const { userCourses } = this.state
я проверяю всегда, вроде работает

2017-04-19 21:43 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +          <VideoPlayer
!

2017-04-19 21:44 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +    this.props.addVideoId(isEnded = true)
1 ругается линт
2 я хочу обозначить переменную, чтобы не разбираться потом откуда она

2017-04-19 21:44 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +    this.props.addVideoId(isEnded = false)
!

2017-04-19 21:45 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/VideoPlayer.js
> +        {this.renderVideo()}
!

2017-04-20 05:05 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    firebase.database().ref('users/' + uid)
!

2017-04-20 05:05 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    firebase.database().ref('users/' + uid)
!

2017-04-20 05:05 UTC, MsZlets commented on src/routes/MyCourses/components/UserCoursesList.js
> +    firebase.database().ref('users/' + uid)
!

2017-04-20 15:27 UTC, Stas-Buzunko commented on src/routes/MyCourses/components/UserCoursesList.js
> +    firebase.database().ref('users/' + uid)
после мерджа мастера так же не обновляется стейт?

2017-04-20 18:11 UTC, Stas-Buzunko requested changes

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
почему здесь мап который возвращает в некоторых случаях false?
может filter лучше будет?

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +      section.lessonsIds[index + 1] ? section.lessonsIds[(index + 1)] : section.sectionNumber
разнеси нормально на строки, пожалуйста

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +      const nextLessonId = (index === -1) ? false :
нужно ли нам тут false?

как насчет index !== -1 && somethingElse ?

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const NextSectionId = course.sections[(nextId + 1)] ? course.sections[(nextId + 1)].lessonsIds[0] : false
[(nextId + 1)] - почему тут скобки?
аналогично, нужен ли нам тут false? если ты юзаешь только когда true?

например course.sections[nextId + 1] && course.sections[nextId + 1].lessonsIds[0] эквивалентно твоему тернарнику, только короче и читабельнее

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +    const isLessonInWatchedLessonsIds = uniqueWatchedLessonsIds.findIndex(id => id === lessonId)
серьезно) я открыл MDN чтобы глянуть, что это, я знал по find, а про findIndex не знал

2017-04-20 18:11 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/routes/Lesson/components/MainView.js
> +      return ([
супер

2017-04-21 11:58 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
!

2017-04-21 12:11 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const NextSectionId = course.sections[(nextId + 1)] ? course.sections[(nextId + 1)].lessonsIds[0] : false
[(nextId + 1)] - почему тут скобки? без скобок спрашивает что за 1

2017-04-21 12:16 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const NextSectionId = course.sections[(nextId + 1)] ? course.sections[(nextId + 1)].lessonsIds[0] : false
так не работает 
course.sections[(nextId + 1)] && const NextSectionId = course.sections[(nextId + 1)].lessonsIds[0] 
так тоже не работает
const NextSectionId = course.sections[(nextId + 1)] ? course.sections[(nextId + 1)].lessonsIds[0] 
как ты хочешь переписать?

2017-04-21 12:25 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
const findNextLessonIdArray = course.sections.filter((section) => {
      const index = section.lessonsIds.findIndex(item => item === lastLessonId)
      index !== -1 &&
        const nextLessonId = section.lessonsIds[index + 1] ? section.lessonsIds[(index + 1)] : section.sectionNumber
        && return nextLessonId

2017-04-21 12:26 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
так не работает

2017-04-21 12:30 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
и так тоже нет
index !== -1 && return nextLessonId

2017-04-21 12:33 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
етод filter() вызывает переданную функцию callback один раз для каждого элемента, присутствующего в массиве, и конструирует новый массив со всеми значениями, для которых функция callback вернула true или значение, становящееся true при приведении в boolean.

2017-04-21 12:34 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const findNextLessonIdArray = course.sections.map((section) => {
мне нужен не элемент массива, а другое значение, я не знаю, как это сделать с фильтер

2017-04-21 12:40 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +      const nextLessonId = (index === -1) ? false :
оно мне нужно для мап, если у тебя получится переаисать то, что выше с фильтер, я уберу

2017-04-21 12:40 UTC, MsZlets commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +      section.lessonsIds[index + 1] ? section.lessonsIds[(index + 1)] : section.sectionNumber
что ты имеешь в виду?

2017-04-25 12:13 UTC, Stas-Buzunko requested changes

2017-04-25 12:13 UTC, Stas-Buzunko commented on src/routes/MyCourses/routes/Course/components/MainView.js
> +    const watchLessonId = courseFromUser.watchedLessonsIds ? this.countNewWatchLessonId(courseFromUser)
в этой строке баг, firstLessonId пустой

2017-05-12 07:39 UTC, Stas-Buzunko approved these changes

2017-05-12 07:39 UTC, merged