Add popup
Stas-Buzunko/cyber-school pull request #6
Opened 2017-03-20 15:16 UTC by MsZlets

2017-03-23 08:05 UTC, Stas-Buzunko requested changes
Добавь, что при успешном сохранении урока, попап закрывается

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/EditCourse.js
> +                onClick={() => this.editCourse()}
ты забайндила эту функцию в конструкторе, тут не надо стрелку юзать

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      firebase.database().ref('lessons/' + `${id}`)
можно просто id или `lesson/${id}`
оба выглядят странно в одной строке

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +    lessonsIds.map(id => {
map возвращает объект, если тебе не нужно ничего возвращать (ты не записываешь в переменную результат), то используй  forEach

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +          const lessons = this.state.lessons
это не новый объект, а ссылка на стейт

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +            lessons.push(lessonItem)
в итоге здесь у тебя уже в стейте будет новый урок
а так делать плохо

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +          this.setState({ lessons, lessonsLoaded: true })
зарефактори пожалуйста этот метод, можешь посмотреть пример с дрессмейта, когда там грузятся предметы / транзакции и записываются в стейт за 1 раз. map нужно будет юзать

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +    firebase.database().ref('lessons/' + `${lessonKey}`).update({ lesson })
как и с id или 'lessons/' + lessonKey или `lessons/ ${lessonKey}`

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +    lessonsIds.push(lessonKey)
это опять пуш в стейт

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +    lessonsIds.push(lessonKey)
чтобы не было пуша в стейт
делаешь так
const newLessons = [...lessonIds, lessonKey] - тут создается новый объект
this.setState({lesson: newLessons})

или делаешь копию стейта const { lessondsIds } = this.state. но я полностью не уверен, что это будет копия, а не ссылка, но думаю, что да

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/NewCourse.js
> +      lessonsIds: ['-KfpDaBzmb9DfpOUuDSQ', '-KfpDkTklhAjKLC8bRTQ'],
можешь удалить захардкоженые уроки

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/NewCourse.js
> +    lessonsIds.push(lessonKey)
опять пушишь в стейт :)

2017-03-23 08:05 UTC, Stas-Buzunko commented on src/routes/Courses/components/NewCourse.js
> +    this.setState({ lessonsIds })
если не веришь мне, то можешь закоментить эту строку, и все будет работать также

2017-03-27 07:07 UTC, Stas-Buzunko requested changes

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +    this.fetchItems(params.id)
почему Items я бы ожидал что там много айтемов будут загружаться

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +  .then(() => {
это вызовется даже если курс был пустой
как насчет занести это в первую часть if, только тогда когда есть курс?

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +    this.state.course.lessonsIds.forEach(id => {
я не советую юзать state когда он был добавлен только пару строк выше, почему бы не использовать object / course которые у тебя есть выше?

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +        const course = object
какой смысл от этой переменной? может ты хотел добавить айди в курс?)))

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +          this.setState({ lessons: newLessons, lessonsLoaded: true })
проходя по каждому предмету ты делаешь сетСтейт, зачем?)
давай применим Promise.alll
и когда все будут загружены, то в 1 вызов сетСтейта запишем?)
в идеале перенести это в первый if и вообще за 1 сетСтейт все делать

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Course/components/MainView.js
> +          this.setState({ coursesLoaded: true })
скорее всего ты имела ввиду lessonsLoaded ?

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/EditCourse.js
> +    this.fetchCourse(this.state.id)
вообще я почему-то считаю пропсы надежнее чем писать в стейт а потом из него, но это не супер критично, имеет место быть

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/EditCourse.js
> +            lessonsIds: object.lessonsIds
покажи свои знания по деструкторизации :) это должна быть 1 строка вместо 10

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/EditCourse.js
> +                onClick={() => this.editCourse()}
функция уже забайндена, нет смысла в () =>
просто this.editCourse

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +    const lessonsIds = this.props.lessonsIds
хочу увидеть деструктуризацию :)

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +          this.setState({ lessons: newLessons, lessonsLoaded: true })
Было бы круто разефакторить с Promise.all и делать 1 сет стейт

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +          this.setState({ coursesLoaded: true })
lessonsLoaded вместо coursesLoaded ?

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      comments: lesson.comments
хочу тоже увидеть деструктуризацию в 1 строку :)

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      lessons.map(item => {
мап возвращает объект, если не надо возвращать то используй forEach

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      this.props.hideModal('lesson')
это вызовется раньше чем зарезолвятся промисы и окно закроется

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      lessons.map(item => {
я понял что ты хочешь здесь сделать, но это очень грязно)))

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonList.js
> +      lessons.map(item => {
1) делаешь проверку есть ли текущий урок в стейте
2) если нет, то добавляешь (деструктуризация массива)
3) если есть, то нужно убрать старый и на его место добавить новый (деструктуризация)

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/LessonPopupComponent.js
> +        id: lesson.id
деструктуризация

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Courses/components/NewCourse.js
> +  }
?

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Disciplines/components/MainView.js
> +    this.setState({ discipline:params.discipline })
зачем дисциплина в стейте если она всегда есть в пропсах?
на то есть особая причина?
вообще копировать пропсы в стейт плохо

2017-03-27 07:07 UTC, Stas-Buzunko commented on src/routes/Disciplines/index.js
> +  path : 'disciplines/(:discipline)',
1) что означает (:discipline) ? почему вообще добавляют скобки вокруг?)))
2) зачем добавила скобки конкретно в этом случае

2017-03-27 16:06 UTC, MsZlets commented on src/routes/Course/components/MainView.js
> +        const course = object
да, пускай пока побудет так,я уберу в  ветке comments

2017-03-28 19:37 UTC, merged